//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacaoDataAccess
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Aplicacoes
    {
        [DataMember]
        public string Aplicacao { get; set; }
        [DataMember]
        public string Tipo { get; set; }
        [DataMember]
        public string Messagem { get; set; }
        [DataMember]
        public int UserId { get; set; }
        public System.DateTime DateInfo { get; set; }
    }
}
